### ISSUE TITLE
guide/index

### ISSUE THREAD

**Issue by hayeah** [hayeah/vuejs.org#1]
http://rc.vuejs.org/guide/index.html#What-is-Vue-js

**Comment by Mr-Wiredancer** [comment]
我觉得还是用文件来分好一些。比如这个 issue 应该是 guide/index

**Comment by Mr-Wiredancer** [comment]
DDL:0925-23:59

**Comment by Mr-Wiredancer** [comment]
@hymRedemption 重新让其他人认领吧
