### ISSUE TITLE
你们的翻译校对规了么？

### ISSUE THREAD

**Issue by xiaoxiaoyu** [hayeah/vuejs.org#103]

**Comment by Mr-Wiredancer** [comment]
啥意思，没看懂

**Comment by milkmeowo** [comment]
@xiaoxiaoyu 校对过了，是不是有哪里觉得不对，可以提PR

**Comment by Mr-Wiredancer** [comment]
@xiaoxiaoyu i'm closing this if no further discussions

**Comment by xiaoxiaoyu** [comment]
我之前看了好多错，等我再返回看的时候，我看到的错误已经改过了。就没有再回复。
