### ISSUE TITLE
拼写错误

### ISSUE THREAD

**Issue by shareworlds** [hayeah/vuejs.org#105]
可以用特殊的 $evet 变量将它传递给方法，
$evet 单词应该是$event

http://vue.sike.io/v2/guide/events.html

**Comment by shareworlds** [comment]
这样可以确保每个组件的代码都是在相对对立的环境中编写和推理
对立--> 孤立
http://vue.sike.io/v2/guide/components.html

**Comment by shareworlds** [comment]
由父组件向子组件传递数据可以通过 prop 来完成。
prop  ->  props
http://vue.sike.io/v2/guide/components.html

**Comment by shareworlds** [comment]
这些场景的正确解决方式时：
时--> 是
http://vue.sike.io/v2/guide/components.html

**Comment by shareworlds** [comment]
要注意，在 JavaScript 中对象和数组时通过引用传递的。如果属性是数组活着对象，在子组件内修改 会 影响父组件的状态
时 --> 是
活着 --> 或者
http://vue.sike.io/v2/guide/components.html

**Comment by Mr-Wiredancer** [comment]
@shareworlds 明天进行订正

**Comment by Mr-Wiredancer** [comment]
@shareworlds fixed
