### ISSUE TITLE
guide/single-file-components

### ISSUE THREAD

**Issue by hymRedemption** [hayeah/vuejs.org#24]

**Comment by seaify** [comment]
认领掉，deadline: 10.10号

**Comment by seaify** [comment]
@hymRedemption 延迟到10.15号

**Comment by Mr-Wiredancer** [comment]
@seaify @CoderKwong 需要重新分配还是修改日期？

**Comment by seaify** [comment]
不好意思，重新分配下吧, @Mr-Wiredancer

**Comment by Mr-Wiredancer** [comment]
@CoderKwong 看有哪些小伙伴可以领掉这个任务

**Comment by CoderKwong** [comment]
@Mr-Wiredancer 嗯，可能要去找找才行

**Comment by CoderKwong** [comment]
@Mr-Wiredancer 问了一下，没什么人有空，你在群里发一下公告@所有人看看有没有谁有空可以领掉的
