### ISSUE TITLE
guide/routing

### ISSUE THREAD

**Issue by hymRedemption** [hayeah/vuejs.org#25]

**Comment by lsslu** [comment]
认领一发 2016/10/08前完成

**Comment by CoderKwong** [comment]
@lsslu 你好，因为没有你的联系方式，为了方便沟通，麻烦告知一下你的邮箱，或者直接联系一下我，我的email：jiangyanhao1991@gmail.com

**Comment by lsslu** [comment]
lsslu@hotmail.com

**Comment by lsslu** [comment]
@CoderKwong 你好，我的email: lsslu@hotmail.com

**Comment by CoderKwong** [comment]
本来想拉你进微信群的，但是看到你好像已经加入了:)

2016-10-08 5:02 GMT+08:00 lss <notifications@github.com>:
