### ISSUE TITLE
guide/ssr

### ISSUE THREAD

**Issue by hymRedemption** [hayeah/vuejs.org#28]

**Comment by gongph** [comment]
这个给我翻译吧，预计10月15日完成。 @Mr-Wiredancer

**Comment by milkmeowo** [comment]
@gongph 尽快完成

**Comment by Mr-Wiredancer** [comment]
@gongph @milkmeowo @CoderKwong 这个需要重新分配还是调整日期？

**Comment by CoderKwong** [comment]
@Mr-Wiredancer 先等等 @gongph 的回复吧

**Comment by gongph** [comment]
不好意思近两天有事，没上github，今晚我 pr 到主干。

**Comment by gongph** [comment]
@CoderKwong 提交了
