### ISSUE TITLE
我们也进行了一些翻译，请问有没有可以一起协作的？

### ISSUE THREAD

**Issue by dingyiming** [hayeah/vuejs.org#74]
目前我们也进行了一些翻译工作，基本完成，校对工作还需要进一步进行，不知道我们能否一起协助做点什么？
- 发布网址 ： http://vuefe.cn
- 翻译仓库与进度汇总 https://github.com/vuefe/vuejs.org 
- 翻译情况 http://vuefe.cn/about/
- 翻译 issue https://github.com/vuefe/vuejs.org/issues
- Guide 翻译issue https://github.com/vuefe/vuejs.org/issues/1
- API 翻译 issue https://github.com/vuefe/vuejs.org/issues/44

**Comment by Mr-Wiredancer** [comment]
@dingyiming 我们貌似有小伙伴已经私聊你们了。如果没有的话加一下微信 mrwiredancer

**Comment by dingyiming** [comment]
@Mr-Wiredancer 已经收到了，谢谢
